#!/bin/sh

if ! head -1 | grep -qE "^(fix|feat|ci|chore|docs|test|style|refactor|perf|build|revert)(\(.+?\))?: .{1,}$"; then
  echo "Aborting commit. Your commit message is invalid"
  exit 1
fi
if ! head -1 "$1" | grep -qE "^.{1, 88}"; then
  echo "Aborting commit. Your commit message is too long" 
  exit 1
fi